accounts:
  admin: owner
cookie:
  expiry_days: 1
  key: login_cookie_key
  name: login_cookie_name
credentials:
  usernames:
    admin:
      email: admin@gmail.com
      name: admin
      password: $2b$12$0DL83PN0ElcB8nFqSnUxueY9LC4vhdMA6G4cUfZ5ynzpz6YE55Chi
permissions:
  developer:
  owner:
  reviewer:
preauthorized:
  emails:
  - admin@gmail.com